-- Generated by Modeler - do not change.
CREATE TABLE organizations.employees (
    id UUID PRIMARY KEY, 
    first_name VARCHAR(100) NOT NULL, 
    last_name VARCHAR(100) NOT NULL, 
    organization_unit_id UUID NOT NULL
);
