using System.Text;
using Modeler.Views.Common;

namespace Modeler.ComponentsModel.Views.Markdown.ListTable;

public class MarkdownComponentsListTableViewGenerator
{
    private readonly Model _model;
    private readonly IViewOutput _output;

    public MarkdownComponentsListTableViewGenerator(Model model, IViewOutput output)
    {
        _model = model;
        _output = output;
    }

    public void Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by Modeler - do not change. -->");
        sb.AppendLine("|Name|Type|");
        sb.AppendLine("|---|---|");

        var allComponents = _model.GetAllComponents();
        foreach (var component in allComponents)
        {
            sb.AppendLine($"|{component.Name}|{component.Type.Name}|");
        }

        _output.Execute(sb.ToString());
    }
}
