using System.Text;
using Modeler.Views.Common;

namespace Modeler.Messaging.Views.AsciiDoc;

public static class AsciiDocBrokerMessagesListGenerator
{
    public static void Generate(BrokerModel broker, IViewOutput output)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Modeler - do not change.");
        
        sb.AppendLine("|===");
        sb.AppendLine("|Name|Publishers|Subscribers");
        sb.AppendLine();

        var allMessages = broker.GetAllMessages();
        foreach (var message in allMessages)
        {
            var publishers = broker.GetPublishers(message);
            var subscribers = broker.GetSubscribers(message);
            sb.AppendLine($"|{message.Name}");
            sb.AppendLine($"|{string.Join(", ", publishers.Select(x => x.Name).ToList())}");
            sb.AppendLine($"|{string.Join(", ", subscribers.Select(x => x.Name).ToList())}");
            sb.AppendLine();
        }
        
        sb.AppendLine();
        sb.AppendLine("|===");
        
        output.Execute(sb.ToString());
    }
}