using System.Text;
using Modeler.Models.Data;
using Modeler.Models.Data.Structure;
using Modeler.Views.Common.Outputs;
using Modeler.Views.Data.DataModelDiagrams.PlantUml;
using Modeler.Views.Data.Shared;

namespace Modeler.Views.Data.Diagram.PlantUml;

public static class PlantUmlDataModelGenerator
{
    public static void Generate(
        DatabaseComponent model,
        int indentSize,
        List<PlantUmlDataModelView> views, 
        IViewTranslator viewTranslator,
        IMultipleViewsOutput viewsOutput)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by conceptualizer - do not change.");
            sb.AppendLine();

            GenerateTables(sb, model, indentSize, view);
            GenerateViews(sb, model, indentSize, view);
            
            GenerateRelationships(sb, model, view, viewTranslator);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new ViewOutputItem(view, content));
        }
        
        viewsOutput.Execute(outputItems);
    }

    private static void GenerateRelationships(
        StringBuilder sb,
        DatabaseComponent model,
        PlantUmlDataModelView view,
        IViewTranslator viewTranslator)
    {
        foreach (var relationship in model.GetRelationships())
        {
            if (view.VisibleStructureElements.All(x => x.Element != relationship.From) ||
                view.VisibleStructureElements.All(x => x.Element != relationship.To))
            {
                continue;
            }

            const string relationshipType = "-->";

            sb.AppendLine(
                $"\"{relationship.From.Name}\" \"{viewTranslator.TranslateMultiplicity(relationship.FromMultiplicity)}\"" +
                $" {relationshipType} \"{viewTranslator.TranslateMultiplicity(relationship.ToMultiplicity)}\" \"{relationship.To.Name}\" : \"{relationship.GetRelationshipName()}\"");
        }
    }

    private static void GenerateTables(
        StringBuilder sb,
        DatabaseComponent model,
        int indentSize,
        PlantUmlDataModelView view)
    {
        var indent = string.Empty;
        for (int i = 0; i < indentSize; i++)
        {
            indent += " ";
        }

        foreach (var table in model.GetTables().OrderBy(x => x.Name))
        {
            var viewTable = view.VisibleStructureElements.SingleOrDefault(x => x.Element == table);
            if (viewTable == null)
            {
                continue;
            }
            
            GenerateTable(sb, viewTable, indent);
            sb.AppendLine();
        }
    }
    
    private static void GenerateViews(
        StringBuilder sb,
        DatabaseComponent model,
        int indentSize,
        PlantUmlDataModelView view)
    {
        var indent = string.Empty;
        for (int i = 0; i < indentSize; i++)
        {
            indent += " ";
        }

        foreach (var viewElement in model.GetViews().OrderBy(x => x.Name))
        {
            var viewTable = view.VisibleStructureElements.SingleOrDefault(x => x.Element == viewElement);
            if (viewTable == null)
            {
                continue;
            }
            
            GenerateView(sb, viewTable, indent);
            sb.AppendLine();
        }
    }

    private static void GenerateTable(
        StringBuilder sb,
        VisibleStructureElement visibleStructureElement,
        string indent)
    {
        sb.AppendLine($"entity \"{visibleStructureElement.Element.Name}\"" + " {");

        var table = (Table)visibleStructureElement.Element;
        if (visibleStructureElement.ShowColumns)
        {
            foreach (var column in table.Columns.Select(x => x).OrderByDescending(x => x.IsPrimaryKey).ThenBy(x => x.Name))
            {
                var isNullString = column.IsPrimaryKey ? string.Empty : 
                    column.IsNullable ? "NULL" : "NOT NULL";
                var isPrimaryKeyString = column.IsPrimaryKey ? "PK" : string.Empty;
                sb.AppendLine($"{indent}{column.Name}: {column.Type.Name.Replace("(", "[").Replace(")", "]")} {isNullString} {isPrimaryKeyString}");
            }
        }

        sb.AppendLine("}");
    }
    
    private static void GenerateView(
        StringBuilder sb,
        VisibleStructureElement visibleStructureElement,
        string indent)
    {
        sb.AppendLine($"entity \"{visibleStructureElement.Element.Name}\"" + " <<view>> {");

        var table = (View)visibleStructureElement.Element;
        if (visibleStructureElement.ShowColumns)
        {
            foreach (var column in table.Columns.OrderBy(x => x.Name))
            {
                sb.AppendLine($"{indent}{column.Name}: {column.Type.Name}");
            }
        }

        sb.AppendLine("}");
    }
}