using System.Text;

namespace Modeler.StateModel.Views.PlantUml;

public class PlantUmlStateMachineViewGenerator
{
    private readonly IStateMachineViewsOutput<StateMachineView> _stateMachineViewsOutput;

    public PlantUmlStateMachineViewGenerator(
        IStateMachineViewsOutput<StateMachineView> stateMachineViewsOutput)
    {
        _stateMachineViewsOutput = stateMachineViewsOutput;
    }

    public void Generate(
        List<StateMachineView> views)
    {
        var outputItems = new List<StateMachineViewOutputItem<StateMachineView>>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");

            sb.AppendLine();

            GenerateParticipants(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new StateMachineViewOutputItem<StateMachineView>(view.Id, view, content));
        }
        
        _stateMachineViewsOutput.Execute(outputItems);
    }

    private static void GenerateParticipants(StringBuilder sb,
        StateMachineView view)
    {
        foreach (var state in view.StateMachine.GetStates())
        {
            GenerateParticipant(sb, state);

            sb.AppendLine();
        }
    }

    private static void GenerateParticipant(StringBuilder sb,
        State state)
    {
        sb.AppendLine($"state \"{state.Name}\" as {state.Id}");
    }
}