using System.Text;
using Modeler.SequenceModel.Views.Shared;

namespace Modeler.SequenceModel.Views.Mermaid;

public class MermaidSequenceDiagramViewGenerator
{
    private readonly ISequenceDiagramViewsOutput<SequenceDiagramView> _sequenceDiagramViewsOutput;
    private readonly ISequenceDiagramViewTranslator _viewTranslator;

    public MermaidSequenceDiagramViewGenerator(
        ISequenceDiagramViewsOutput<SequenceDiagramView> sequenceDiagramViewsOutput,
        ISequenceDiagramViewTranslator viewTranslator)
    {
        _sequenceDiagramViewsOutput = sequenceDiagramViewsOutput;
        _viewTranslator = viewTranslator;
    }

    public void Generate(
        List<SequenceDiagramView> views)
    {
        var outputItems = new List<SequenceDiagramViewOutputItem<SequenceDiagramView>>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("sequenceDiagram");
            sb.AppendLine("%%Generated by Modeler - do not change.");
            if (view.AutonumberMessages)
            {
                sb.AppendLine("autonumber"); 
            }

            sb.AppendLine();

            GenerateParticipants(sb, view, _viewTranslator);

            GenerateMessages(sb, view);

            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new SequenceDiagramViewOutputItem<SequenceDiagramView>(view.Id, view, content));
        }
        
        _sequenceDiagramViewsOutput.Execute(outputItems);
    }
    
    private void GenerateMessages(StringBuilder sb, SequenceDiagramView view)
    {
        foreach (var message in view.Sequence.GetMessages())
        {
            if (view.ParticipantsToShow.All(x => x != message.Sender) || view.ParticipantsToShow.All(x => x != message.Receiver))
            {
                continue;
            }

            string? messageArrow = null;
            if (message.Type is SynchronousRequestMessage or SelfMessage)
            {
                messageArrow = "->>";
            }

            if (message.Type is SynchronousResponseMessage)
            {
                messageArrow = "-->>";
            }
            
            if (message.Type is EventMessage)
            {
                messageArrow = "-)";
            }

            if (messageArrow == null)
            {
                throw new Exception("Unknown message type");
            }
            
            sb.AppendLine($"{message.Sender.Id} {messageArrow} {message.Receiver.Id} : {message.Name} {_viewTranslator.TranslateMessageParameters(message.Parameters)}");
            
            if (message.Type is SynchronousRequestMessage)
            {
                sb.AppendLine($"activate {message.Receiver.Id}");
                sb.AppendLine();
            }

            if (message.Type is SynchronousResponseMessage)
            {
                sb.AppendLine($"deactivate {message.Sender.Id}");
                sb.AppendLine();
            }
        }
    }

    private static void GenerateParticipants(StringBuilder sb,
        SequenceDiagramView view,
        ISequenceDiagramViewTranslator viewTranslator)
    {
        foreach (var participant in view.ParticipantsToShow)
        {
            GenerateParticipant(sb, participant, viewTranslator);

            sb.AppendLine();
        }
    }

    private static void GenerateParticipant(StringBuilder sb,
        Participant participant,
        ISequenceDiagramViewTranslator viewTranslator)
    {
        var participantType = viewTranslator.TranslateParticipantType(participant.Type);
        if (participantType != "participant" && participantType != "actor")
        {
            participantType = "participant";
        }
        
        sb.AppendLine($"{participantType} {participant.Id} as {participant.Name} <<{viewTranslator.TranslateParticipantStereoType(participant.Type)}>>");
    }
}