using System.Text;
using Modeler.DataModel.Structure;
using Modeler.Views.Common;

namespace Modeler.DataModel.PostgreSQL.Views.SQL.Generator;

public class PostgreSqlStructureViewsGenerator
{
    private IMultipleViewsOutput _viewsOutput;

    public PostgreSqlStructureViewsGenerator(IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
    }

    public void Generate(List<SqlStructureElementView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views.Where(x => x.Element.GetType().IsAssignableTo(typeof(Table))).ToList())
        {
            var tableContent = GenerateTable((Table)view.Element);
            outputItems.Add(new ViewOutputItem(view, tableContent));
        }
        
        _viewsOutput.Execute(outputItems);
    }

    private static string GenerateTable(Table table)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by Modeler - do not change.");
        sb.AppendLine($"CREATE TABLE {table.Schema.Name}.{table.Name} (");
        int columnGenerated = 0;
        foreach (var column in table.Columns)
        {
            columnGenerated++;

            string columnTypeConstraintsText;
            if (column.IsPrimaryKey)
            {
                columnTypeConstraintsText = "PRIMARY KEY";
            }
            else if (column.IsNullable)
            {
                columnTypeConstraintsText = "NULL";
            }
            else
            {
                columnTypeConstraintsText = "NOT NULL";
            }

            if (columnGenerated == table.Columns.Count)
            {
                sb.AppendLine($"    {column.Name} {column.Type.Name} {columnTypeConstraintsText}");
            }
            else
            {
                sb.AppendLine($"    {column.Name} {column.Type.Name} {columnTypeConstraintsText}, ");
            }
        }

        sb.AppendLine(");");

        return sb.ToString();
    }
}