using System.Text;
using Modeler.Models.Components;
using Modeler.Models.Components.Relationships;
using Modeler.Views.Common.Outputs;
using Modeler.Views.Components.Common;

namespace Modeler.Views.Components.Diagram;

public class PlantComponentsDiagramViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    private readonly Model _model;

    private readonly IComponentsDiagramViewLayout _viewLayout;

    private List<IComponent> _components;

    private readonly IComponentsViewTranslator _translator;
    
    private readonly IPlantUmlComponentDiagramRelationshipGenerator _plantUmlComponentDiagramRelationshipGenerator;

    public PlantComponentsDiagramViewGenerator(
        Model model,
        IMultipleViewsOutput viewsOutput,
        IComponentsDiagramViewLayout viewLayout,
        IComponentsViewTranslator translator,
        IPlantUmlComponentDiagramRelationshipGenerator plantUmlComponentDiagramRelationshipGenerator)
    {
        _viewsOutput = viewsOutput;
        _viewLayout = viewLayout;
        _translator = translator;
        _plantUmlComponentDiagramRelationshipGenerator = plantUmlComponentDiagramRelationshipGenerator;
        _model = model;
        _components = new List<IComponent>();
    }

    public void Generate(
        List<PlantUmlComponentsDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();

        foreach (var view in views)
        {
            _components = new List<IComponent>();
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            sb.AppendLine("skinparam componentStyle rectangle");
            sb.AppendLine();

            var componentTypes = _model.GetComponentTypes();
            sb.AppendLine("skinparam component {");
            foreach (var componentType in componentTypes)
            {
                var backgroundColor = _viewLayout.GetComponentTypeColor(componentType);
                if (backgroundColor != string.Empty)
                {
                    sb.AppendLine($"{GetIndentText(1)}BackgroundColor<<{componentType.Name}>> {backgroundColor}");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();

            GenerateComponents(sb, view);
            GenerateRelationships(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();

            outputItems.Add(new ViewOutputItem(view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private string GetIndentText(int indentLevel)
    {
        var indentText = string.Empty;
        for (int i = 0; i < indentLevel * _viewLayout.IndentSize; i++)
        {
            indentText += " ";
        }

        return indentText;
    }

    private void GenerateComponents(
        StringBuilder sb,
        PlantUmlComponentsDiagramView view)
    {
        foreach (var visibleComponent in view.VisibleComponents.OrderBy(x => x.Component.Name))
        {
            GenerateComponent(
                sb, 
                view,
                visibleComponent.Component, -1, visibleComponent.NestedComponentsLevel);

            sb.AppendLine();
        }
    }

    private void GenerateComponent(
        StringBuilder sb,
        PlantUmlComponentsDiagramView view,
        IComponent visibleComponent,
        int indentLevel,
        int nestedLevel)
    {
        if (view.HiddenComponents.Contains(visibleComponent))
        {
            return;
        }
        
        _components.Add(visibleComponent);
        indentLevel += 1;
        nestedLevel -= 1;
        var indentText = GetIndentText(indentLevel);
        sb.AppendLine($"{indentText}component \"{visibleComponent.Name}\" <<{visibleComponent.Type.Name}>>" + " {");

        if (nestedLevel >= 0)
        {
            var subComponents = _model.GetSubComponents(visibleComponent);
            foreach (var subComponent in subComponents)
            {
                GenerateComponent(sb, view, subComponent, indentLevel, nestedLevel);
            }
        }

        sb.AppendLine($"{indentText}}}");
    }

    private void GenerateRelationships(StringBuilder sb, PlantUmlComponentsDiagramView view)
    {
        var allRelationships = _model.GetRelationships();
        var relationshipsToShow = new List<ComponentRelationship>();
        foreach (var component in _components)
        {
            var allSubComponents = _model.GetAllSubComponents(component);

            var componentRelationships = allRelationships.Where(x =>
                    x.Source == component && _components.Select(y => y).Contains(x.Target))
                .ToList();
            foreach (var relationship in componentRelationships)
            {
                var isHidden = view.HiddenRelationships.Any(x =>
                    x.Source == relationship.Source && x.Target == relationship.Target);
                if (isHidden)
                {
                    continue;
                }
                
                var relationshipForNestedComponent = false;
                foreach (var subComponent in allSubComponents)
                {
                    if (allRelationships.Any(x => x.Source == subComponent &&
                                                  x.Target == relationship.Target &&
                                                  _components.Select(y => y).Contains(subComponent)))
                    {
                        relationshipForNestedComponent = true;
                        break;
                    }
                }

                var targetSubComponents = _model.GetAllSubComponents(relationship.Target);
                foreach (var subComponent in targetSubComponents)
                {
                    if (allRelationships.Any(x => x.Source == component && x.Target == subComponent && _components.Select(y => y).Contains(subComponent)))
                    {
                        relationshipForNestedComponent = true;
                        break;
                    }
                }

                if (!relationshipForNestedComponent)
                {
                    relationshipsToShow.Add(relationship);
                }
            }
        }

        foreach (var componentRelationship in relationshipsToShow)
        {
            var generated = _plantUmlComponentDiagramRelationshipGenerator.Generate(componentRelationship, sb);
            if (generated)
            {
                continue;
            }
            if (componentRelationship is UsageComponentRelationship usageComponentRelationship)
            {
                GenerateForUsage(
                    sb,
                    usageComponentRelationship);
            }

            if (componentRelationship is DependencyComponentRelationship dependencyComponentRelationship)
            {
                GenerateForDependency(
                    sb,
                    dependencyComponentRelationship);
            }
            
            if (componentRelationship is PublishSubscribeRelationship publishSubscribeRelationship)
            {
                GenerateForPublishSubscribe(
                    sb,
                    publishSubscribeRelationship);
            }

            if (componentRelationship is AssociationComponentRelationship associationComponentRelationship)
            {
                GenerateForAssociation(
                    sb,
                    associationComponentRelationship);
            }
        }
    }

    private static void GenerateForAssociation(StringBuilder sb, AssociationComponentRelationship relationship)
    {
        string label = relationship.Name != null ? $": {relationship.Name}" : string.Empty;
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" {label}");
    }
    
    private void GenerateForPublishSubscribe(StringBuilder sb, PublishSubscribeRelationship relationship)
    {
        var label = _translator.TranslateSourceToTargetRelationshipName(relationship);
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" ..> \"{relationship.Target.Name}\" : {label}");
    }

    private void GenerateForUsage(StringBuilder sb, UsageComponentRelationship relationship)
    {
        var label = _translator.TranslateSourceToTargetRelationshipName(relationship);
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" : {label}");
    }

    private void GenerateForDependency(StringBuilder sb, DependencyComponentRelationship relationship)
    {
        var label = _translator.TranslateSourceToTargetRelationshipName(relationship);
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" ..> \"{relationship.Target.Name}\" : {label}");
    }
}