using System.Text;
using Modeler.Models.Components;
using Modeler.Models.RestApi;
using Modeler.Views.Common.Outputs;
using Modeler.Views.Components.ComponentsDiagram;

namespace Modeler.Views.Components.Diagram;

public class PlantComponentsDiagramViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    private readonly Model _model;

    private readonly IComponentsDiagramViewLayout _viewLayout;

    private List<IComponent> _components;

    public PlantComponentsDiagramViewGenerator(
        Model model,
        IMultipleViewsOutput viewsOutput,
        IComponentsDiagramViewLayout viewLayout)
    {
        _viewsOutput = viewsOutput;
        _viewLayout = viewLayout;
        _model = model;
        _components = new List<IComponent>();
    }

    public void Generate(
        List<PlantUmlComponentsDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();

        foreach (var view in views)
        {
            _components = new List<IComponent>();
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            sb.AppendLine("skinparam componentStyle rectangle");
            sb.AppendLine();

            var componentTypes = _model.GetComponentTypes();
            sb.AppendLine("skinparam component {");
            foreach (var componentType in componentTypes)
            {
                var backgroundColor = _viewLayout.GetComponentTypeColor(componentType);
                if (backgroundColor != string.Empty)
                {
                    sb.AppendLine($"{GetIndentText(1)}BackgroundColor<<{componentType.Name}>> {backgroundColor}");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();

            GenerateComponents(sb, view);
            //  GenerateInterfaces(sb, view);
            GenerateRelationships(sb, view);
            GenerateApisRelationships(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();

            outputItems.Add(new ViewOutputItem(view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private void GenerateApisRelationships(StringBuilder sb, PlantUmlComponentsDiagramView view)
    {
        var components = _components;

        foreach (var component in components)
        {
            // if (component is IApiProvider apiProvider)
            // {
            //     string label = "provides";
            //     sb.AppendLine(
            //         $"\"{component.Name}\" --> \"{apiProvider.ProvidedApi.Id}\" : {label}");
            // }

            if (component is IApiConsumer apiConsumer)
            {
                string label = "uses";
                sb.AppendLine(
                    $"\"{component.Name}\" --> \"{apiConsumer.ConsumingApi.Id}\" : {label}");
            }
        }
    }

    private string GetIndentText(int indentLevel)
    {
        var indentText = string.Empty;
        for (int i = 0; i < indentLevel * _viewLayout.IndentSize; i++)
        {
            indentText += " ";
        }

        return indentText;
    }

    private void GenerateComponents(
        StringBuilder sb,
        PlantUmlComponentsDiagramView view)
    {
        foreach (var visibleComponent in view.VisibleComponents.OrderBy(x => x.Component.Name))
        {
            GenerateComponent(sb, visibleComponent.Component, -1, visibleComponent.NestedComponentsLevel);

            sb.AppendLine();
        }
    }

    // private void GenerateInterfaces(
    //     StringBuilder sb,
    //     ComponentsDiagramView view)
    // {
    //     var interfaces = new List<IApiModel>();
    //     var components = GetAllComponents(view);
    //     interfaces.AddRange(components.OfType<IApiProvider>().Select(x => x.ProvidedApi).ToList());
    //     interfaces.AddRange(components.OfType<IApiConsumer>().Select(x => x.ConsumingApi).ToList());
    //     interfaces = interfaces.Distinct().ToList();
    //     foreach (var @interface in interfaces)
    //     {
    //         GenerateInterface(sb, @interface);
    //
    //         sb.AppendLine();
    //     }
    // }

    private List<IComponent> GetAllComponents(PlantUmlComponentsDiagramView view)
    {
        var components = view.VisibleComponents.Select(x => x.Component).ToList();
        foreach (var component in view.VisibleComponents.Select(x => x.Component))
        {
            components.AddRange(_model.GetAllSubComponents(component));
        }

        return components;
    }

    private void GenerateComponent(
        StringBuilder sb,
        IComponent visibleComponent,
        int indentLevel,
        int nestedLevel)
    {
        _components.Add(visibleComponent);
        indentLevel += 1;
        nestedLevel -= 1;
        var indentText = GetIndentText(indentLevel);
        sb.AppendLine($"{indentText}component \"{visibleComponent.Name}\" <<{visibleComponent.Type.Name}>>" + " {");

        if (visibleComponent is IApiProvider apiProvider)
        {
            GenerateInterface(sb, apiProvider.ProvidedApi);
        }

        if (nestedLevel >= 0)
        {
            var subComponents = _model.GetSubComponents(visibleComponent);
            foreach (var subComponent in subComponents)
            {
                GenerateComponent(sb, subComponent, indentLevel, nestedLevel);
            }
        }

        sb.AppendLine($"{indentText}}}");
    }

    private void GenerateInterface(
        StringBuilder sb,
        IApiModel api)
    {
        sb.AppendLine($"interface \"{api.Name}\" as {api.Id}");
    }

    private void GenerateRelationships(StringBuilder sb, PlantUmlComponentsDiagramView view)
    {
        var allRelationships = _model.GetRelationships();
        var relationshipsToShow = new List<ComponentRelationship>();
        foreach (var component in _components)
        {
            var allSubComponents = _model.GetAllSubComponents(component);

            var componentRelationships = allRelationships.Where(x =>
                    x.Source == component && _components.Select(y => y).Contains(x.Target))
                .ToList();
            foreach (var relationship in componentRelationships)
            {
                var relationshipForNestedComponent = false;
                foreach (var subComponent in allSubComponents)
                {
                    if (allRelationships.Any(x => x.Source == subComponent &&
                                                  x.Target == relationship.Target &&
                                                  _components.Select(y => y).Contains(subComponent)) )
                    {
                        relationshipForNestedComponent = true;
                        break;
                    }
                }

                if (!relationshipForNestedComponent)
                {
                    relationshipsToShow.Add(relationship);
                }
            }
        }

        foreach (var componentRelationship in relationshipsToShow)
        {
            if (componentRelationship is UsageComponentRelationship usageComponentRelationship)
            {
                GenerateForUsage(
                    sb,
                    usageComponentRelationship);
            }

            if (componentRelationship is DependencyComponentRelationship dependencyComponentRelationship)
            {
                GenerateForDependency(
                    sb,
                    dependencyComponentRelationship);
            }

            if (componentRelationship is AssociationComponentRelationship associationComponentRelationship)
            {
                GenerateForAssociation(
                    sb,
                    associationComponentRelationship);
            }
        }
    }

    private static void GenerateForAssociation(StringBuilder sb, AssociationComponentRelationship relationship)
    {
        string label = relationship.Name != null ? $": {relationship.Name}" : string.Empty;
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" {label}");
    }

    private static void GenerateForUsage(StringBuilder sb, UsageComponentRelationship relationship)
    {
        if (relationship is {Source: IApiConsumer apiConsumer, Target: IApiProvider apiProvider})
        {
            if (apiConsumer.ConsumingApi == apiProvider.ProvidedApi)
            {
                return;
            }
        }

        string label = "use";
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" : {label}");
    }

    private static void GenerateForDependency(StringBuilder sb, DependencyComponentRelationship relationship)
    {
        string label = "dependency";
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" ..> \"{relationship.Target.Name}\" : {label}");
    }
}