using System.Text;
using Modeler.ComponentsModel;
using Modeler.RestApiModel;
using Modeler.Views.Common;

namespace Modeler.Views.Components.ComponentsDiagram;

public class PlantComponentsDiagramViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    private readonly Model _model;

    private readonly IComponentsDiagramViewLayout _viewLayout;

    public PlantComponentsDiagramViewGenerator(
        Model model,
        IMultipleViewsOutput viewsOutput,
        IComponentsDiagramViewLayout viewLayout)
    {
        _viewsOutput = viewsOutput;
        _viewLayout = viewLayout;
        _model = model;
    }

    public void Generate(
        List<PlantUmlComponentsDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            sb.AppendLine("skinparam componentStyle rectangle");
            sb.AppendLine();

            var componentTypes = _model.GetComponentTypes();
            sb.AppendLine("skinparam component {");
            foreach (var componentType in componentTypes)
            {
                var backgroundColor = _viewLayout.GetComponentTypeColor(componentType);
                if (backgroundColor != string.Empty)
                {
                    sb.AppendLine($"{GetIndentText(1)}BackgroundColor<<{componentType.Name}>> {backgroundColor}");
                }
            }
            sb.AppendLine("}");
            sb.AppendLine();

            GenerateComponents(sb, view);
          //  GenerateInterfaces(sb, view);
            GenerateRelationships(sb, view);
            GenerateApisRelationships(sb, view);
            
            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new ViewOutputItem(view, content));
        }
        
        _viewsOutput.Execute(outputItems);
    }

    private void GenerateApisRelationships(StringBuilder sb, PlantUmlComponentsDiagramView view)
    {
        var components = GetAllComponents(view);

        foreach (var component in components)
        {
            // if (component is IApiProvider apiProvider)
            // {
            //     string label = "provides";
            //     sb.AppendLine(
            //         $"\"{component.Name}\" --> \"{apiProvider.ProvidedApi.Id}\" : {label}");
            // }
            
            if (component is IApiConsumer apiConsumer)
            {
                string label = "uses";
                sb.AppendLine(
                    $"\"{component.Name}\" --> \"{apiConsumer.ConsumingApi.Id}\" : {label}");
            }
        }
    }

    private string GetIndentText(int indentLevel)
    {
        var indentText = string.Empty;
        for (int i = 0; i < indentLevel * _viewLayout.IndentSize; i++)
        {
            indentText += " ";
        }

        return indentText;
    }
    
    private void GenerateComponents(
        StringBuilder sb,
        PlantUmlComponentsDiagramView view)
    {
        foreach (var component in view.Components.OrderBy(x => x.Name))
        {
            GenerateComponent(sb, component, -1);

            sb.AppendLine();
        }
    }
    
    // private void GenerateInterfaces(
    //     StringBuilder sb,
    //     ComponentsDiagramView view)
    // {
    //     var interfaces = new List<IApiModel>();
    //     var components = GetAllComponents(view);
    //     interfaces.AddRange(components.OfType<IApiProvider>().Select(x => x.ProvidedApi).ToList());
    //     interfaces.AddRange(components.OfType<IApiConsumer>().Select(x => x.ConsumingApi).ToList());
    //     interfaces = interfaces.Distinct().ToList();
    //     foreach (var @interface in interfaces)
    //     {
    //         GenerateInterface(sb, @interface);
    //
    //         sb.AppendLine();
    //     }
    // }

    private List<IComponent> GetAllComponents(PlantUmlComponentsDiagramView view)
    {
        var components = view.Components.ToList();
        foreach (var component in view.Components)
        {
            components.AddRange(_model.GetAllSubComponents(component));
        }

        return components;
    }

    private void GenerateComponent(
        StringBuilder sb,
        IComponent component,
        int indentLevel)
    {
        indentLevel += 1;
        var indentText = GetIndentText(indentLevel);
        sb.AppendLine($"{indentText}component \"{component.Name}\" <<{component.Type.Name}>>" + " {");

        if (component is IApiProvider apiProvider)
        {
            GenerateInterface(sb, apiProvider.ProvidedApi);
        }

        var subComponents = _model.GetSubComponents(component);

        foreach (var subComponent in subComponents)
        {
            GenerateComponent(sb, subComponent, indentLevel);
        }

        sb.AppendLine($"{indentText}}}");
    }
    
    private void GenerateInterface(
        StringBuilder sb,
        IApiModel api)
    {
        sb.AppendLine($"interface \"{api.Name}\" as {api.Id}");
    }
    
    private void GenerateRelationships(StringBuilder sb, PlantUmlComponentsDiagramView view)
    {
        foreach (var relationship in _model.GetRelationships())
        {
            bool showSource = false;
            
            if (view.Components.Contains(relationship.Source))
            {
                showSource = true;
            }
            else
            {
                foreach (var viewComponent in view.Components)
                {
                    if(_model.GetAllSubComponents(viewComponent).Contains(relationship.Source))
                    {
                        showSource = true;
                    }
                }
            }
            
            bool showTarget = false;
            
            if (view.Components.Contains(relationship.Target))
            {
                showTarget = true;
            }
            else
            {
                foreach (var viewComponent in view.Components)
                {
                    if(_model.GetAllSubComponents(viewComponent).Contains(relationship.Target))
                    {
                        showTarget = true;
                    }
                }
            }
            
            if (!showSource || !showTarget)
            {
                continue;
            }

            if (relationship is UsageComponentRelationship usageComponentRelationship)
            {
                GenerateForUsage(
                    sb,
                    usageComponentRelationship);
            }
            
            if (relationship is DependencyComponentRelationship dependencyComponentRelationship)
            {
                GenerateForDependency(
                    sb,
                    dependencyComponentRelationship);
            }
            
            if (relationship is AssociationComponentRelationship associationComponentRelationship)
            {
                GenerateForAssociation(
                    sb,
                    associationComponentRelationship);
            }
        }
    }
    
    private static void GenerateForAssociation(StringBuilder sb, AssociationComponentRelationship relationship)
    {
        string label = relationship.Name != null ? $": {relationship.Name}" : string.Empty;
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" {label}");
    }
    
    private static void GenerateForUsage(StringBuilder sb, UsageComponentRelationship relationship)
    {
        if (relationship is {Source: IApiConsumer apiConsumer, Target: IApiProvider apiProvider})
        {
            if (apiConsumer.ConsumingApi == apiProvider.ProvidedApi)
            {
                return;
            }
        }
        string label = "use";
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" --> \"{relationship.Target.Name}\" : {label}");
    }
    
    private static void GenerateForDependency(StringBuilder sb, DependencyComponentRelationship relationship)
    {
        string label = "dependency";
        sb.AppendLine(
            $"\"{relationship.Source.Name}\" ..> \"{relationship.Target.Name}\" : {label}");
    }
}