using System.Text;
using Modeler.ComponentsModel.Views.Shared;

namespace Modeler.ComponentsModel.Views.AsciiDoc.Details;

public class AsciiDocComponentsDetailsViewsGenerator
{
    private readonly IViewsOutput<AsciiDocComponentDetailsView> _viewsOutput;

    private readonly Model _model;

    public AsciiDocComponentsDetailsViewsGenerator(Model model, IViewsOutput<AsciiDocComponentDetailsView> viewsOutput)
    {
        _viewsOutput = viewsOutput;
        _model = model;
    }

    public void Generate(
        List<AsciiDocComponentDetailsView> views)
    {
        var outputItems = new List<ViewOutputItem<AsciiDocComponentDetailsView>>();
        foreach (var view in views)
        {
            var content = Generate(view);

            outputItems.Add(new ViewOutputItem<AsciiDocComponentDetailsView>(view.Id, view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private string Generate(AsciiDocComponentDetailsView view)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Modeler - do not change.");

        sb.AppendLine("|===");
        sb.AppendLine("|Relation|Component|Type");
        sb.AppendLine();

        var relationships = _model.GetComponentRelationships(view.Component);

        foreach (var relationship in relationships)
        {
            if (relationship.Source == view.Component)
            {
                sb.AppendLine($"|{TranslateRelationshipName(relationship, true)}");
                sb.AppendLine($"|{relationship.Target.Name}");
                sb.AppendLine($"|{relationship.Target.Type.Name}");
                sb.AppendLine();
            }
            else if (relationship.Target == view.Component)
            {
                sb.AppendLine($"|{TranslateRelationshipName(relationship, false)}");
                sb.AppendLine($"|{relationship.Source.Name}");
                sb.AppendLine($"|{relationship.Source.Type.Name}");
                sb.AppendLine();
            }
            else if (_model.Contains(view.Component, relationship.Source) && relationship is not DependencyComponentRelationship)
            {
                sb.AppendLine($"|{TranslateRelationshipName(relationship, true)}");
                sb.AppendLine($"|{relationship.Target.Name}");
                sb.AppendLine($"|{relationship.Target.Type.Name}");
                sb.AppendLine();
            }
        }

        sb.AppendLine("|===");

        return sb.ToString();
    }

    private string TranslateRelationshipName(ComponentRelationship relationship, bool isSource)
    {
        if (relationship is UsageComponentRelationship)
        {
            return isSource ? "Use" : "Is used by";
        }
        
        if (relationship is ContainsComponentRelationship)
        {
            return isSource ? "Contains" : "Is contained by";
        }
        
        if (relationship is DependencyComponentRelationship)
        {
            return isSource ? "Depends on" : "Dependent of";
        }
        
        return string.Empty;
    }
}