using System.Text;
using Modeler.Views.Common;

namespace Modeler.ComponentsModel.Views.AsciiDoc.ListTable;

public class AsciiDocComponentsListTableViewGenerator
{
    private readonly Model _model;

    private readonly IViewOutput _output;

    public AsciiDocComponentsListTableViewGenerator(
        Model model,
        IViewOutput output)
    {
        _model = model;
        _output = output;
    }

    public void Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Modeler - do not change.");
        
        sb.AppendLine("|===");
        sb.AppendLine("|Name|Type");
        sb.AppendLine();

        var allComponents = _model.GetAllComponents();
        foreach (var component in allComponents)
        {
            sb.AppendLine($"|{component.Name}");
            sb.AppendLine($"|{component.Type.Name}");
            sb.AppendLine();
        }
        
        sb.AppendLine();
        sb.AppendLine("|===");
        
        _output.Execute(sb.ToString());
    }
}