using System.Text;

namespace Modeler.SequenceModel.Views.PlantUml;

public class PlantUmlSequenceDiagramViewGenerator
{
    private readonly IViewsOutput<SequenceDiagramView> _viewsOutput;
    private readonly IPlantUmlSequenceDiagramViewTranslator _viewTranslator;
    private readonly IPlantUmlSequenceDiagramViewLayout _viewLayout;

    public PlantUmlSequenceDiagramViewGenerator(
        IViewsOutput<SequenceDiagramView> viewsOutput,
        IPlantUmlSequenceDiagramViewTranslator viewTranslator, 
        IPlantUmlSequenceDiagramViewLayout viewLayout)
    {
        _viewsOutput = viewsOutput;
        _viewTranslator = viewTranslator;
        _viewLayout = viewLayout;
    }

    public void Generate(
        List<SequenceDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem<SequenceDiagramView>>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            if (view.AutonumberMessages)
            {
                sb.AppendLine("autonumber"); 
            }

            sb.AppendLine();

            GenerateParticipants(sb, view, _viewTranslator, _viewLayout);

            GenerateMessages(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new ViewOutputItem<SequenceDiagramView>(view.Id, view, content));
        }
        
        _viewsOutput.Execute(outputItems);
    }
    
    private void GenerateMessages(StringBuilder sb, SequenceDiagramView view)
    {
        foreach (var message in view.Sequence.GetMessages())
        {
            if (view.ParticipantsToShow.All(x => x != message.Sender) || view.ParticipantsToShow.All(x => x != message.Receiver))
            {
                continue;
            }

            string? messageArrow = null;
            if (message.Type is SynchronousRequestMessage or SelfMessage)
            {
                messageArrow = "->";
            }

            if (message.Type is SynchronousResponseMessage)
            {
                messageArrow = "-->";
            }
            
            if (message.Type is EventMessage)
            {
                messageArrow = "->>";
            }

            if (messageArrow == null)
            {
                throw new Exception("Unknown message type");
            }
            
            sb.AppendLine($"{message.Sender.Id} {messageArrow} {message.Receiver.Id} : {message.Name} {_viewTranslator.TranslateMessageParameters(message.Parameters)}");
            
            if (message.Type is SynchronousRequestMessage)
            {
                sb.AppendLine($"activate {message.Receiver.Id}");
                sb.AppendLine();
            }

            if (message.Type is SynchronousResponseMessage)
            {
                sb.AppendLine($"deactivate {message.Sender.Id}");
                sb.AppendLine();
            }
        }
    }

    private static void GenerateParticipants(StringBuilder sb,
        SequenceDiagramView view,
        IPlantUmlSequenceDiagramViewTranslator viewTranslator,
        IPlantUmlSequenceDiagramViewLayout viewLayout)
    {
        foreach (var participant in view.ParticipantsToShow)
        {
            GenerateParticipant(sb, participant, viewTranslator, viewLayout);

            sb.AppendLine();
        }
    }

    private static void GenerateParticipant(StringBuilder sb,
        Participant participant,
        IPlantUmlSequenceDiagramViewTranslator viewTranslator,
        IPlantUmlSequenceDiagramViewLayout viewLayout)
    {
        var participantType = viewTranslator.TranslateParticipantType(participant.Type);
        sb.AppendLine($"{participantType} \"{participant.Name}\" as {participant.Id} <<{viewTranslator.TranslateParticipantStereoType(participant.Type)}>> {viewLayout.GetParticipantColor(participant.Type)}");
    }
}