using System.Text;
using Modeler.Models.Activity;
using Modeler.Views.Activity.Diagram.Shared;
using Modeler.Views.Common.Outputs;

namespace Modeler.Views.Activity.Diagram.PlantUml;

public class PlantUmlActivityDiagramViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    public PlantUmlActivityDiagramViewGenerator(IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
    }

    public void Generate(List<ActivityDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();

        foreach (var view in views)
        {
            var content = BuildDiagram(view.Flow);
            outputItems.Add(new ViewOutputItem(view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private static string BuildDiagram(ActivityFlow flow)
    {
        var sb = new StringBuilder();
        sb.AppendLine("@startuml");
        sb.AppendLine("'Generated by Modeler - do not change.");
        sb.AppendLine();

        DeclareNodes(sb, flow);

        sb.AppendLine($"(*) --> {GetNodeAlias(flow.StartNode)}");

        foreach (var transition in flow.GetTransitions())
        {
            var label = string.IsNullOrWhiteSpace(transition.Label)
                ? string.Empty
                : $" : {Escape(transition.Label)}";

            var targetAlias = transition.Target == null
                ? "(*)"
                : GetNodeAlias(transition.Target);

            sb.AppendLine($"{GetNodeAlias(transition.Source)} --> {targetAlias}{label}");
        }

        sb.AppendLine();
        sb.AppendLine("@enduml");
        sb.AppendLine();

        return sb.ToString();
    }

    private static void DeclareNodes(StringBuilder sb, ActivityFlow flow)
    {
        foreach (var action in flow.GetActions())
        {
            sb.AppendLine($"\"{Escape(action.Name)}\" as {GetNodeAlias(action)}");
        }

        foreach (var decision in flow.GetDecisions())
        {
            sb.AppendLine($"\"{Escape(decision.Name)}\" as {GetNodeAlias(decision)}");
        }

        sb.AppendLine();
    }

    private static string GetNodeAlias(ActivityNode node) => node.Id.ToLowerInvariant();

    private static string Escape(string value) => value.Replace("\"", "\\\"");
}
