using System.Text;
using Modeler.Models.Components;
using Modeler.Models.Components.Relationships;
using Modeler.Views.Common;
using Modeler.Views.Common.Outputs;
using Modeler.Views.Components.Common;

namespace Modeler.Views.Components.Details.Markdown;

public class MarkdownComponentsDetailsViewsGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;
    
    private readonly Model _model;
    
    private readonly IComponentsViewTranslator _translator;

    public MarkdownComponentsDetailsViewsGenerator(Model model, IMultipleViewsOutput viewsOutput, IComponentsViewTranslator translator)
    {
        _viewsOutput = viewsOutput;
        _translator = translator;
        _model = model;
    }

    public void Generate(List<MarkdownComponentDetailsView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var content = Generate(view);
            outputItems.Add(new ViewOutputItem(view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private string Generate(MarkdownComponentDetailsView view)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by Modeler - do not change. -->");
        sb.AppendLine("|Relation|Component|Type|");
        sb.AppendLine("|---|---|---|");
        
        var relationships = _model.GetComponentRelationships(view.Component);

        foreach (var relationship in relationships)
        {
            if (relationship.Source == view.Component)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, true)}");
                sb.Append($"|{relationship.Target.Name}");
                sb.Append($"|{relationship.Target.Type.Name}");
                sb.AppendLine("|");
            }
            else if (relationship.Target == view.Component)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, false)}");
                sb.Append($"|{relationship.Source.Name}");
                sb.Append($"|{relationship.Source.Type.Name}");
                sb.AppendLine("|");
            }
            else if (_model.Contains(view.Component, relationship.Source) && relationship is not DependencyComponentRelationship)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, true)}");
                sb.Append($"|{relationship.Target.Name}");
                sb.Append($"|{relationship.Target.Type.Name}");
                sb.AppendLine("|");
            }
        }

        return sb.ToString();
    }
    
    private string TranslateRelationshipName(ComponentRelationship relationship, bool isSource)
    {
        return isSource ? 
            _translator.TranslateSourceToTargetRelationshipName(relationship) : 
            _translator.TranslateTargetToSourceRelationshipName(relationship);
    }
}
