using System.Text;
using Modeler.ComponentsModel;
using Modeler.Views.Common;

namespace Modeler.Views.Components.Details.Markdown;

public class MarkdownComponentsDetailsViewsGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;
    private readonly Model _model;

    public MarkdownComponentsDetailsViewsGenerator(Model model, IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
        _model = model;
    }

    public void Generate(List<MarkdownComponentDetailsView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var content = Generate(view);
            outputItems.Add(new ViewOutputItem(view, content));
        }

        _viewsOutput.Execute(outputItems);
    }

    private string Generate(MarkdownComponentDetailsView view)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by Modeler - do not change. -->");
        sb.AppendLine("|Relation|Component|Type|");
        sb.AppendLine("|---|---|---|");
        
        var relationships = _model.GetComponentRelationships(view.Component);

        foreach (var relationship in relationships)
        {
            if (relationship.Source == view.Component)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, true)}");
                sb.Append($"|{relationship.Target.Name}");
                sb.Append($"|{relationship.Target.Type.Name}");
                sb.AppendLine("|");
            }
            else if (relationship.Target == view.Component)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, false)}");
                sb.Append($"|{relationship.Source.Name}");
                sb.Append($"|{relationship.Source.Type.Name}");
                sb.AppendLine("|");
            }
            else if (_model.Contains(view.Component, relationship.Source) && relationship is not DependencyComponentRelationship)
            {
                sb.Append($"|{TranslateRelationshipName(relationship, true)}");
                sb.Append($"|{relationship.Target.Name}");
                sb.Append($"|{relationship.Target.Type.Name}");
                sb.AppendLine("|");
            }
        }

        return sb.ToString();
    }
    
    private string TranslateRelationshipName(ComponentRelationship relationship, bool isSource)
    {
        if (relationship is UsageComponentRelationship)
        {
            return isSource ? "Use" : "Is used by";
        }
        
        if (relationship is ContainsComponentRelationship)
        {
            return isSource ? "Contains" : "Is contained by";
        }
        
        if (relationship is DependencyComponentRelationship)
        {
            return isSource ? "Depends on" : "Dependent of";
        }
        
        return string.Empty;
    }
}
