using System.Text;
using Modeler.StateModel;
using Modeler.Views.Common;

namespace Modeler.Views.StateMachine.Diagram.PlantUml;

public class PlantUmlStateMachineViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    public PlantUmlStateMachineViewGenerator(IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
    }

    public void Generate(
        List<PlantUmlStateMachineDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");

            sb.AppendLine();

            GenerateStates(sb, view);
            
            GenerateTransitions(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new ViewOutputItem(view, content));
        }
        
        _viewsOutput.Execute(outputItems);
    }

    private static void GenerateTransitions(StringBuilder sb, PlantUmlStateMachineDiagramView diagramView)
    {
        foreach (var transition in diagramView.StateMachine.GetTransitions())
        {
            var fromStateId = transition.FromState is InitialState ? "[*]" : transition.FromState.Id;
            var toStateId = transition.ToState is EndState ? "[*]" : transition.ToState.Id;
            string transitionName = transition.Event.Name != string.Empty ? $" : {transition.Event.Name}" : string.Empty;
            sb.AppendLine($"{fromStateId} --> {toStateId}{transitionName}");
        }
    }

    private static void GenerateStates(StringBuilder sb,
        PlantUmlStateMachineDiagramView diagramView)
    {
        foreach (var state in diagramView.StateMachine.GetStates())
        {
            GenerateState(sb, state);

            sb.AppendLine();
        }
    }

    private static void GenerateState(StringBuilder sb,
        State state)
    {
        sb.AppendLine($"state \"{state.Name}\" as {state.Id}");
    }
}