using System.Collections.Generic;
using System.Linq;
using System.Text;
using Modeler.Models.Components;
using Modeler.Models.Deployment;
using Modeler.Views.Common.Outputs;
using Model = Modeler.Models.Deployment.Model;

namespace Modeler.Views.Deployment.Diagram;

public class PlantDeploymentDiagramViewGenerator
{
    private const string EnvironmentStereotype = "DeploymentEnvironment";
    private const string ServerStereotype = "DeploymentServer";
    private const string RuntimeStereotype = "DeploymentRuntime";

    private readonly Model _model;
    private readonly IMultipleViewsOutput _viewsOutput;
    private readonly IDeploymentDiagramViewLayout _viewLayout;

    public PlantDeploymentDiagramViewGenerator(
        Model model,
        IMultipleViewsOutput viewsOutput,
        IDeploymentDiagramViewLayout viewLayout)
    {
        _model = model;
        _viewsOutput = viewsOutput;
        _viewLayout = viewLayout;
    }

    public void Generate(List<PlantUmlDeploymentDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();

        foreach (var view in views)
        {
            var sb = new StringBuilder();
            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            sb.AppendLine("skinparam componentStyle rectangle");
            sb.AppendLine("skinparam packageStyle rectangle");
            sb.AppendLine();

            foreach (var visibleEnvironment in view.VisibleEnvironments.OrderBy(x => x.Environment.Name))
            {
                GenerateEnvironment(sb, view, visibleEnvironment, -1);
                sb.AppendLine();
            }

            sb.AppendLine("@enduml");
            sb.AppendLine();

            outputItems.Add(new ViewOutputItem(view, sb.ToString()));
        }

        _viewsOutput.Execute(outputItems);
    }

    private void GenerateEnvironment(
        StringBuilder sb,
        PlantUmlDeploymentDiagramView view,
        VisibleDeploymentEnvironment visibleEnvironment,
        int indentLevel)
    {
        indentLevel += 1;
        var indentText = GetIndentText(indentLevel);
        var environment = visibleEnvironment.Environment;
        sb.AppendLine($"{indentText}package \"{environment.Name}\" as {environment.Id} <<{EnvironmentStereotype}>> {{");

        if (visibleEnvironment.NestedLevel >= 1)
        {
            var servers = _model.GetServers(environment)
                .Where(server => !view.HiddenServers.Contains(server))
                .OrderBy(server => server.Name)
                .ToList();

            foreach (var server in servers)
            {
                GenerateServer(sb, view, server, indentLevel, visibleEnvironment.NestedLevel - 1);
            }
        }

        sb.AppendLine($"{indentText}}}");
    }

    private void GenerateServer(
        StringBuilder sb,
        PlantUmlDeploymentDiagramView view,
        DeploymentServer server,
        int indentLevel,
        int nestedLevel)
    {
        indentLevel += 1;
        var indentText = GetIndentText(indentLevel);
        sb.AppendLine($"{indentText}node \"{server.Name}\" as {server.Id} <<{ServerStereotype}>> {{");

        if (nestedLevel >= 1)
        {
            var runtimes = _model.GetRuntimeEnvironments(server)
                .Where(runtime => !view.HiddenRuntimeEnvironments.Contains(runtime))
                .OrderBy(runtime => runtime.Name)
                .ToList();

            foreach (var runtime in runtimes)
            {
                GenerateRuntime(sb, view, runtime, indentLevel, nestedLevel - 1);
            }
        }

        sb.AppendLine($"{indentText}}}");
    }

    private void GenerateRuntime(
        StringBuilder sb,
        PlantUmlDeploymentDiagramView view,
        DeploymentRuntimeEnvironment runtimeEnvironment,
        int indentLevel,
        int nestedLevel)
    {
        indentLevel += 1;
        var indentText = GetIndentText(indentLevel);
        sb.AppendLine($"{indentText}component \"{runtimeEnvironment.Name}\" as {runtimeEnvironment.Id} <<{RuntimeStereotype}>> {{");

        if (nestedLevel >= 1)
        {
            var components = _model.GetComponents(runtimeEnvironment)
                .Where(component => !view.HiddenComponents.Contains(component))
                .OrderBy(component => component.Name)
                .ToList();

            foreach (var component in components)
            {
                var componentIndentText = GetIndentText(indentLevel + 1);
                sb.AppendLine($"{componentIndentText}component \"{component.Name}\" as {component.Id} <<{component.Type.Name}>>");
            }
        }

        sb.AppendLine($"{indentText}}}");
    }

    private string GetIndentText(int indentLevel)
    {
        if (indentLevel < 0)
        {
            return string.Empty;
        }

        return new string(' ', indentLevel * _viewLayout.IndentSize);
    }
}
