<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Components\Views\Details\" />
      <Folder Include="Conceptual\Views\ConceptDetails\" />
      <Folder Include="EventsFlow\Views\EventsFlowDiagrams\" />
      <Folder Include="EventsFlow\Views\TableList\" />
      <Folder Include="State\Views\StateMachineTable\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Modeler\Modeler.csproj" />
    </ItemGroup>

</Project>
