using System.Text;
using Modeler.Views.Common;

namespace Modeler.Views.RestApi.EndpointsList.AsciiDoc;

public class AsciiDocEndpointsViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    public AsciiDocEndpointsViewGenerator(IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
    }

    public void Generate(List<AsciiDocEndpointsView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by Modeler - do not change.");
            sb.AppendLine("|===");
            sb.AppendLine("|Name|Method|Path|Request|Response");
            sb.AppendLine();
            foreach (var ep in view.Model.GetEndpoints())
            {
                sb.AppendLine($"|{ep.Name}");
                sb.AppendLine($"|{ep.Method}");
                sb.AppendLine($"|{ep.Path}");
                sb.AppendLine($"|{ep.RequestModel?.Name}");
                sb.AppendLine($"|{ep.ResponseModel?.Name}");
                sb.AppendLine();
            }
            sb.AppendLine("|===");
            outputItems.Add(new ViewOutputItem(view, sb.ToString()));
        }
        _viewsOutput.Execute(outputItems);
    }
}
