using System.Text;

namespace Modeler.StateModel.Views.Markdown;

public class StateMachineMarkdownTableViewGenerator
{
    private readonly IStateMachineMarkdownTableViewsOutput<StateMachineMarkdownTableView> _output;

    public StateMachineMarkdownTableViewGenerator(
        IStateMachineMarkdownTableViewsOutput<StateMachineMarkdownTableView> output)
    {
        _output = output;
    }

    public void Generate(List<StateMachineMarkdownTableView> views)
    {
        var outputItems = new List<StateMachineMarkdownTableViewsOutputItem<StateMachineMarkdownTableView>>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<!-- Generated by Modeler - do not change. -->");
            sb.AppendLine();

            var states = view.StateMachine.GetStates();
            sb.Append("|Event \\ Source State|");
            foreach (var state in states)
            {
                sb.Append($"{state.Name}|");
            }
            sb.AppendLine();
            sb.Append("|---|");
            foreach (var _ in states)
            {
                sb.Append("---|");
            }
            sb.AppendLine();

            var transitionEvents = view.StateMachine.GetTransitionEvents();
            var transitions = view.StateMachine.GetTransitions();

            foreach (var transitionEvent in transitionEvents)
            {
                sb.Append($"|{transitionEvent.Name}|");
                foreach (var state in states)
                {
                    var transition = transitions.SingleOrDefault(x => x.FromState == state && x.Event == transitionEvent);
                    if (transition != null)
                    {
                        sb.Append($"{transition.ToState.Name}|");
                    }
                    else
                    {
                        sb.Append("X|");
                    }
                }
                sb.AppendLine();
            }

            var content = sb.ToString();
            outputItems.Add(new StateMachineMarkdownTableViewsOutputItem<StateMachineMarkdownTableView>(view.Id, view, content));
        }

        _output.Execute(outputItems);
    }
}
