using System.Text;
using Modeler.Views.Common;
using Modeler.Views.Common.Outputs;

namespace Modeler.Views.RestApi.ApiModelsList.AsciiDoc;

public class AsciiDocApiModelsViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;

    public AsciiDocApiModelsViewGenerator(IMultipleViewsOutput viewsOutput)
    {
        _viewsOutput = viewsOutput;
    }

    public void Generate(List<AsciiDocApiModelsView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by Modeler - do not change.");
            foreach (var model in view.Model.GetApiObjectModels())
            {
                sb.AppendLine($"[#rest_api_model_{model.Id}]");
                sb.AppendLine($"=== {model.Name}");
                sb.AppendLine();
                sb.AppendLine("[cols=3*]");
                sb.AppendLine("|===");
                sb.AppendLine("|Name|Type|Required");
                sb.AppendLine();
                foreach (var attr in model.Attributes)
                {
                    sb.AppendLine($"|{attr.Name}");
                    sb.AppendLine($"|{attr.Type.Name}");
                    sb.AppendLine($"|{(attr.Required ? "YES" : "NO")}");
                    sb.AppendLine();
                }
                sb.AppendLine("|===");
                sb.AppendLine();
            }
            outputItems.Add(new ViewOutputItem(view, sb.ToString()));
        }
        _viewsOutput.Execute(outputItems);
    }
}
