using System.Text;

namespace Modeler.StateModel.Views.AsciiDoc;

public class StateMachineAsciiDocTableViewGenerator
{
    private readonly IStateMachineAsciiDocTableViewsOutput<StateMachineAsciiDocTableView> 
        _stateMachineViewsOutput;

    public StateMachineAsciiDocTableViewGenerator(
        IStateMachineAsciiDocTableViewsOutput<StateMachineAsciiDocTableView> stateMachineViewsOutput)
    {
        _stateMachineViewsOutput = stateMachineViewsOutput;
    }

    public void Generate(
        List<StateMachineAsciiDocTableView> views)
    {
        var outputItems = new List<StateMachineAsciiDocTableViewsOutputItem<StateMachineAsciiDocTableView>>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("//Generated by Modeler - do not change.");
            
            sb.AppendLine();
            
            sb.AppendLine("|===");
            sb.AppendLine();

            var states = view.StateMachine.GetStates();
            sb.Append("|Event \\ Source State");
            foreach (var state in states)
            {
                sb.Append($"|{state.Name}");
            }
            
            sb.AppendLine();
            sb.AppendLine();
            var transitionEvents = view.StateMachine.GetTransitionEvents();
            var transitions = view.StateMachine.GetTransitions();

            foreach (var transitionEvent in transitionEvents)
            {
                sb.AppendLine($"|{transitionEvent.Name}");
                foreach (var state in states)
                {
                    var transition = transitions.SingleOrDefault(x => x.FromState == state && x.Event == transitionEvent);
                    if (transition != null)
                    {
                        sb.AppendLine($"|{transition.ToState.Name}");
                    }
                    else
                    {
                        sb.AppendLine("|X");
                    }
                }
                sb.AppendLine();
            }
            
            sb.AppendLine();
            
            sb.AppendLine("|===");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new StateMachineAsciiDocTableViewsOutputItem<StateMachineAsciiDocTableView>(view.Id, view, content));
        }
        
        _stateMachineViewsOutput.Execute(outputItems);
    }
}