using System.Text;
using Modeler.Models.Sequence.Messages.Types;
using Modeler.Models.Sequence.Participants;
using Modeler.Views.Common;
using Modeler.Views.Common.Outputs;
using Modeler.Views.Sequence.Diagram.Shared;

namespace Modeler.Views.Sequence.Diagram.PlantUml;

public class PlantUmlSequenceDiagramViewGenerator
{
    private readonly IMultipleViewsOutput _viewsOutput;
    private readonly ISequenceDiagramViewTranslator _viewTranslator;
    private readonly ISequenceDiagramViewLayout _viewLayout;

    public PlantUmlSequenceDiagramViewGenerator(
        IMultipleViewsOutput viewsOutput,
        ISequenceDiagramViewTranslator viewTranslator, 
        ISequenceDiagramViewLayout viewLayout)
    {
        _viewsOutput = viewsOutput;
        _viewTranslator = viewTranslator;
        _viewLayout = viewLayout;
    }

    public void Generate(
        List<SequenceDiagramView> views)
    {
        var outputItems = new List<ViewOutputItem>();
        foreach (var view in views)
        {
            var sb = new StringBuilder();

            sb.AppendLine("@startuml");
            sb.AppendLine("'Generated by Modeler - do not change.");
            if (view.AutonumberMessages)
            {
                sb.AppendLine("autonumber"); 
            }

            sb.AppendLine();

            GenerateParticipants(sb, view, _viewTranslator, _viewLayout);

            GenerateMessages(sb, view);

            sb.AppendLine();
            sb.AppendLine("@enduml");
            sb.AppendLine();

            var content = sb.ToString();
            
            outputItems.Add(new ViewOutputItem(view, content));
        }
        
        _viewsOutput.Execute(outputItems);
    }
    
    private void GenerateMessages(StringBuilder sb, SequenceDiagramView view)
    {
        foreach (var message in view.Sequence.GetMessages())
        {
            if (view.ParticipantsToShow.All(x => x != message.Sender) || view.ParticipantsToShow.All(x => x != message.Receiver))
            {
                continue;
            }

            string? messageArrow = null;
            if (message.Type is SynchronousRequestMessage or SelfMessage)
            {
                messageArrow = "->";
            }

            if (message.Type is SynchronousResponseMessage)
            {
                messageArrow = "-->";
            }
            
            if (message.Type is EventMessage)
            {
                messageArrow = "->>";
            }

            if (messageArrow == null)
            {
                throw new Exception("Unknown message type");
            }
            
            if (message.Type is SynchronousRequestMessage)
            {
                sb.AppendLine($"{message.Sender.Id} {messageArrow} {message.Receiver.Id} : {message.Name}({message.Content})");
                sb.AppendLine($"activate {message.Receiver.Id}");
                sb.AppendLine();
            }

            if (message.Type is SynchronousResponseMessage)
            {
                sb.AppendLine($"{message.Sender.Id} {messageArrow} {message.Receiver.Id} : {message.Name} : {message.Content}");
                sb.AppendLine($"deactivate {message.Sender.Id}");
                sb.AppendLine();
            }
            
            if (message.Type is EventMessage)
            {
                sb.AppendLine($"{message.Sender.Id} {messageArrow} {message.Receiver.Id} : Publish({message.Name})");
                sb.AppendLine();
            }
        }
    }

    private static void GenerateParticipants(StringBuilder sb,
        SequenceDiagramView view,
        ISequenceDiagramViewTranslator viewTranslator,
        ISequenceDiagramViewLayout viewLayout)
    {
        foreach (var participant in view.ParticipantsToShow)
        {
            GenerateParticipant(sb, participant, viewTranslator, viewLayout);

            sb.AppendLine();
        }
    }

    private static void GenerateParticipant(StringBuilder sb,
        ISequenceParticipant participant,
        ISequenceDiagramViewTranslator viewTranslator,
        ISequenceDiagramViewLayout viewLayout)
    {
        var participantType = viewTranslator.TranslateParticipantType(participant.ParticipantType);
        sb.AppendLine($"{participantType} \"{participant.Name}\" as {participant.Id} <<{viewTranslator.TranslateParticipantStereoType(participant.ParticipantType)}>> {viewLayout.GetParticipantColor(participant.ParticipantType)}");
    }
}